### ISSUE TITLE
Should probablly tell people they need to install git

### ISSUE THREAD

**Issue by kurumushi** [Morganamilo/paru#280] opened 2021-03-14 07:08 UTC
### Affected Version
v1.3.0

### Description
Downloaded the paru binary on a fresh install of arch, no git installed yet, paru fails with the error "no such file or directory." I figured out pretty quickly that it was missing git, but I'd assume other users could use a more relevant error message. Or possibly offer to install git for them.

### Output

```
$ ./paru paru
1 aur/paru 1.3.0-1 [+121 ~43.57]
    Feature packed AUR helper
2 aur/paru-bin 1.3.0-1 [+31 ~10.11]
    Feature packed AUR helper
3 aur/paru-git 1.3.0.r3.gc9431b4-1 [+5 ~2.62]
    Feature packed AUR helper
:: Packages to install (eg: 1 2 3, 1-3):
:: 1
:: Resolving dependencies...

:: There are 2 providers available for cargo:
:: Repository extra:
    1) rust  
:: Repository community:
    2) rustup  
Enter a number (default=1): 
:: Calculating conflicts...
:: Calculating inner conflicts...

Repo (4) perl-error-0.17029-2  perl-timedate-2.33-2  
    perl-mailtools-2.21-4  git-2.30.2-1
Repo Make (1) rust-1:1.50.0-2
Aur (1) paru-1.3.0-1

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
error: No such file or directory (os error 2)


```

**Comment by trevorgunn** [comment] 2021-03-14 17:23
1. This is possibly a duplicate of the discussion in #114 
2. `git` is already included as a dependency in the `paru{,-bin,-git}` PKGBUILDS hosted on the AUR.
3. If you follow the provided [instructions](https://github.com/Morganamilo/paru#installation) you should have already installed git before installing paru.

**Comment by Morganamilo** [comment] 2021-03-20 18:10
If you're going to build paru locally and not use the pkgbuild then you're on your own for things like this.

**Closed by Morganamilo** 2021-03-20 18:10 UTC
