### ISSUE TITLE
paru 1.3.0 aarch64 build fails on ArchLinuxArm

### ISSUE THREAD

**Issue by ava1ar** [Morganamilo/paru#258] opened 2021-02-21 00:32 UTC
### Description
Trying to build paru 1.3.0 on ArchLinuxARM and getting exception during the build

```sh
   Compiling raur v5.0.0
error: failed to run custom build command for `markup5ever v0.10.0`

Caused by:
  process didn't exit successfully: `/home/ava1ar/paru/src/paru-1.3.0/target/release/build/markup5ever-97f6883505274a82/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("trailing characters", line: 10, column: 35)', /home/ava1ar/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/markup5ever-0.10.0/build.rs:99:65
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by ajalberd** [comment] 2021-02-21 22:23
Cortex-A53 here. 

Build hangs on "Building [=======================> ] 245/246: paru(bin)" and errors out 

<details>
  <summary>
    summary
  </summary>
  Caused by:
  process didn't exit successfully: `rustc --crate-name paru --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=f02d6c8a9bd39936 -C extra-filename=-f02d6c8a9bd39936 --out-dir /home/alarm/paru/src/paru-1.2.2/target/release/deps -L dependency=/home/alarm/paru/src/paru-1.2.2/target/release/deps --extern alpm=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libalpm-5bb3a231fdd665c9.rlib --extern alpm_utils=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libalpm_utils-6f206a5ebd9a8ed2.rlib --extern ansi_term=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libansi_term-d12243b479b87ec3.rlib --extern anyhow=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libanyhow-bd75342cc7a8dbe2.rlib --extern atty=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libatty-1f3d10b06d5fc8eb.rlib --extern aur_depends=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libaur_depends-0d259b6435482b2d.rlib --extern aur_fetch=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libaur_fetch-8e42178e4681ad8e.rlib --extern chrono=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libchrono-6a6f88786cc4d57a.rlib --extern cini=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libcini-8b2a20a5ea31b14a.rlib --extern dirs=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libdirs-b0a98d417fa10264.rlib --extern futures=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libfutures-6b78a6ea69d1f1e3.rlib --extern globset=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libglobset-85286e0e975822fc.rlib --extern htmlescape=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libhtmlescape-9abce2a4d2460b10.rlib --extern indicatif=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libindicatif-70aa0327ece4cd45.rlib --extern kuchiki=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libkuchiki-d1c815c58fe9401c.rlib --extern nix=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libnix-3689df95ce0c02a4.rlib --extern once_cell=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libonce_cell-fe26a7bfba331492.rlib --extern pacmanconf=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libpacmanconf-fa7e18bdf4695fee.rlib --extern raur=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libraur-f406b7b94b0922f5.rlib --extern reqwest=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libreqwest-c0e289ba037c1f49.rlib --extern rss=/home/alarm/paru/src/paru-1.2.2/target/release/deps/librss-1c975caac40e3d21.rlib --extern serde=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libserde-70419397afe05c73.rlib --extern serde_json=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libserde_json-010263de50f4f3b3.rlib --extern smart_default=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libsmart_default-a848ac0a3a479520.so --extern srcinfo=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libsrcinfo-d17de3cf77d31876.rlib --extern tempfile=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libtempfile-4d0aceaaf551c45e.rlib --extern term_size=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libterm_size-d0854bd0e1b3c18b.rlib --extern tokio=/home/alarm/paru/src/paru-1.2.2/target/release/deps/libtokio-bbed325a3696bdfe.rlib --extern url=/home/alarm/paru/src/paru-1.2.2/target/release/deps/liburl-4179acfe15dc0777.rlib` (signal: 9, SIGKILL: kill)
==> ERROR: A failure occurred in build().
    Aborting...`
</details>

`Compiling paru v1.2.2 (/home/alarm/paru/src/paru-1.2.2)
error: could not compile paru

**Comment by Morganamilo** [comment] 2021-02-24 11:27
The second error is probably just out of memory. First one, I have no idea. Probably something wrong on markup5ever's side. However the CI build did pass.

**Comment by timbell87** [comment] 2021-02-26 05:13
This was supposedly fixed in issue #117 (it clearly wasn't)

Temporary fix I posted before:
add the following to PKGBUILD just above "cargo build..."
```
sed -i '/lto.\+/c\lto = false' Cargo.toml
```

I'm currently able to get it to build on a Pi 3 Model B+ by doing this.

**Comment by Morganamilo** [comment] 2021-02-26 09:53
The "fix" is to use the binry package.

**Comment by timbell87** [comment] 2021-02-27 07:30
Okay, so I'm a noob and didn't know how this worked so for anyone else like myself that passes by
```
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si
```
instead of the instructions in the readme and you can install it without needing to wait forever for it to compile.

The hack is still useful if you're running 32-bit as I've tried that and got it to work and it doesn't look like we have a 32-bit arm image yet.

@Morganamilo Would I be correct in guessing that Raspberry Pi 2 and 3 just aren't quite up to the job of compiling this and probably need it to be cross-compiled on a more powerful machine for the time being?

**Comment by Morganamilo** [comment] 2021-02-27 10:48
There's no 32 bit images right now due to some weird bug with in the build environment.

I assume paru will build fine on rpi 2 if you disable LTO.

**Comment by timbell87** [comment] 2021-02-28 08:03
> There's no 32 bit images right now due to some weird bug with in the build environment.
> 
> I assume paru will build fine on rpi 2 if you disable LTO.

I can confirm this, I tested it on a Pi 2 model B before posting.

**Comment by theslimshaney** [comment] 2021-03-07 23:01
I don't know how rust dependencies work, or even if a newer version of the package will help, But it seems like this codepath hasn't been at line 99 since https://github.com/servo/html5ever/commit/204655#diff-aef89230087849cf7f5813edf3949342c3a0956b7d40b044748bfaa102efa21eR101 then got replaced entirely in https://github.com/servo/html5ever/commit/3afd8d#diff-aef89230087849cf7f5813edf3949342c3a0956b7d40b044748bfaa102efa21eL101

So how to get the package updated in paru?

**Comment by theslimshaney** [comment] 2021-03-08 09:20
FYI I work around this issue by also cloning html5ever (and kuchiki so it doesn't build outdated markup5ever). I did not get the build error after building the latest versions. I built in chroot but I think it should build on native too
Sharing here for others who run into the `failed to run custom build command for markup5ever v0.10.0` and want a fix before whenever the repos get updated. [paru-git.PKGBUILD.zip](https://github.com/Morganamilo/paru/files/6100224/paru-git.PKGBUILD.zip)

**Comment by Morganamilo** [comment] 2021-03-09 12:51
Thing is the arm build succeeded for the 1.4 release. So I'm not sure why it doesn't build for you. I don't have native machine to test it on,

If the deps have pushed a new version then you can update it in the cargo.toml and see if it fixes it.

**Comment by theslimshaney** [comment] 2021-03-10 03:47
The copy of markup5ever that caused error that me and OP see https://github.com/servo/html5ever/blob/8dd03f2aff3eaaef1b60e6b8cf24005e8f99d866/markup5ever/Cargo.toml
And the copy of markup5ever that I was able to use to get rid of the error https://github.com/servo/html5ever/blob/master/markup5ever/Cargo.toml
Are both the same cargo version 0.10.0, so I don't know how to force the new version through cargo (I assume you can't).

Although the CI build seems to be using the old version as well (It's pulling in serde dependencies), so not sure why it doesn't build either ¯\\\_(ツ)_/¯
I'll try and look more into it out if I get time but at least building the dependency straight from repo fixes for now.

**Comment by Loader009** [comment] 2021-03-14 17:41
That's weird.

I tried to install paru 1.3.0 with paru (so basically I tried to build) and ran into the very same issue.

Now I have prepared a new rootfs and set it up with pacstrap and chrooted into it.
I could build paru within that new system without any issues.

So I think that's some caching issue, I haven't tried to debug it yet.
System: aarch64 (renegade elite roc-rk3399-pc)

**Comment by Loader009** [comment] 2021-03-15 20:29
Issue still exists with 1.4.0.
I tried to delete the cache, to lower `MAKEFLAGS="-j2"` (from nprocs) - but cargo or makepkg ignores that and uses all my cores (6 cores) and I haven't notices that my memory is running low (4G RAM).
```
$ free -h
               total        used        free      shared  buff/cache   available
Mem:           3.8Gi       423Mi       1.6Gi        12Mi       1.8Gi       3.3Gi
Swap:             0B          0B          0B
```
Nothing in the journal, I am out of ideas...

`RUSTFLAGS="-C opt-level=2 -C target-cpu=native"`
cache -> ~/.cargo/registry

**Comment by Morganamilo** [comment] 2021-03-15 20:53
I have no idea what the error or but the aarch64 binaries succeed. So I have no clue why it's failing on other people's machines.

**Comment by timbell87** [comment] 2021-03-30 03:10
I just got a clean build of 1.4.0-1 using a Pi 2 Model B without disabling LTO, is anyone able to check if this works on anything else that was failing or at least an actual 64-bit device?

**Comment by jclds139** [comment] 2021-04-09 16:57
It very much still fails on a Pi 4. Same error from serde_json trying to read the entities file and panicking. I think the big issues is that markup5ever stopped using serde_json to parse the entities file but hasn't had a release since that change was made. I'm raising an issue with them about that, and then it just needs to be updated in the dependencies.

**Comment by theslimshaney** [comment] 2021-04-09 17:02
It still doesn't make sense why CI builds pulling in the same outdated version succeeds, but thanks for opening the issue to get their release updated.

**Comment by Morganamilo** [comment] 2021-05-03 12:53
Is this fixed now?

**Comment by jclds139** [comment] 2021-05-03 21:01
It looks like it. I got 1.5.1 to build after m5e's update with some manual tweaking and 1.6.0 just built successfully on my Pi 4.

**Comment by Loader009** [comment] 2021-05-04 05:52
It also builds 1.6.0 successfully on my aarch64 system.

**Comment by Morganamilo** [comment] 2021-05-04 06:01
Nice.

**Closed by Morganamilo** 2021-05-04 06:01 UTC
