### ISSUE TITLE
Panic message when installing a package with unavailable dependencies

### ISSUE THREAD

**Issue by willemw12** [Morganamilo/paru#395] opened 2021-06-02 13:41 UTC
paru-bin: paru v1.7.0 - libalpm v13.0.0

    $ paru -S terra-bzr
    :: Resolving dependencies...

    thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/morganamilo/.cargo/registry/src/github.com-1ecc6299db9ec823/alpm-2.0.0/src/utils.rs:7:10
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    error: could not find all required packages:
        python2-dbus (wanted by: terra-bzr)

The result is correct, however, paru should not print a panic message.

**Comment by Morganamilo** [comment] 2021-06-02 13:52
Duplicate of #392

**Closed by Morganamilo** 2021-06-02 13:52 UTC
