### ISSUE TITLE
libalpm.so.14 cannot be found with pacman in [testing]

### ISSUE THREAD

**Issue by jlo62** [Morganamilo/paru#1239] opened 2024-09-11 10:12 UTC
### Affected Version
2.0.3-1

### Description
`paru` is broken with the `pacman` version that is currently in testing (`7.0.0.r3.g7736133-1`). It bumps the `libalpm` lib version to `15.0.0`

### Output
```paru: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory```

**Comment by kug3lblitz** [comment] 2024-09-11 14:47
Temporary workaround - create a symlink for now until there's an update.

sudo ln -s /usr/lib/libalpm.so.15.0.0 /usr/lib/libalpm.so.14

Worked for me, and I'll just remove the symlink when it's not needed anymore

**Comment by Spixmaster** [comment] 2024-09-14 11:49
A rebuild does not work.

```sh
==> Beginne build()...
   Compiling proc-macro2 v1.0.79
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.153
   Compiling memchr v2.7.1
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling pkg-config v0.3.30
   Compiling cc v1.0.90
   Compiling once_cell v1.19.0
   Compiling ppv-lite86 v0.2.17
   Compiling siphasher v0.3.11
   Compiling pin-project-lite v0.2.13
   Compiling bitflags v2.4.2
   Compiling serde v1.0.197
   Compiling quote v1.0.35
   Compiling log v0.4.21
   Compiling futures-core v0.3.30
   Compiling syn v2.0.52
   Compiling itoa v1.0.10
   Compiling bytes v1.5.0
   Compiling slab v0.4.9
   Compiling futures-sink v0.3.30
   Compiling getrandom v0.2.12
   Compiling vcpkg v0.2.15
   Compiling phf_shared v0.10.0
   Compiling rand_core v0.6.4
   Compiling futures-channel v0.3.30
   Compiling rand_chacha v0.3.1
   Compiling futures-io v0.3.30
   Compiling pin-utils v0.1.0
   Compiling futures-task v0.3.30
   Compiling alpm-sys v3.0.0 (https://github.com/archlinux/alpm.rs?rev=306342#306342ef)
   Compiling equivalent v1.0.1
   Compiling rand v0.8.5
   Compiling hashbrown v0.14.3
   Compiling aho-corasick v1.1.2
   Compiling tracing-core v0.1.32
   Compiling signal-hook-registry v1.4.1
   Compiling num_cpus v1.16.0
   Compiling openssl-sys v0.9.101
   Compiling mio v0.8.11
   Compiling socket2 v0.5.6
   Compiling phf_generator v0.10.0
   Compiling indexmap v2.2.5
   Compiling phf_codegen v0.10.0
   Compiling smallvec v1.13.1
   Compiling tinyvec_macros v0.1.1
   Compiling foreign-types-shared v0.1.1
   Compiling syn v1.0.109
   Compiling fnv v1.0.7
   Compiling crossbeam-utils v0.8.19
   Compiling openssl v0.10.64
   Compiling adler v1.0.2
   Compiling regex-syntax v0.8.2
   Compiling miniz_oxide v0.7.2
   Compiling http v0.2.12
   Compiling foreign-types v0.3.2
   Compiling tinyvec v1.6.0
   Compiling tracing v0.1.40
   Compiling lock_api v0.4.11
   Compiling percent-encoding v2.3.1
   Compiling parking_lot_core v0.9.9
   Compiling new_debug_unreachable v1.0.4
   Compiling crc32fast v1.4.0
   Compiling httparse v1.8.0
   Compiling native-tls v0.2.11
   Compiling unicode-normalization v0.1.23
   Compiling form_urlencoded v1.2.1
   Compiling phf_shared v0.11.2
   Compiling unicode-bidi v0.3.15
   Compiling thiserror v1.0.58
   Compiling scopeguard v1.2.0
   Compiling openssl-probe v0.1.5
   Compiling try-lock v0.2.5
   Compiling want v0.3.1
   Compiling phf_generator v0.11.2
   Compiling regex-automata v0.4.6
   Compiling idna v0.5.0
   Compiling http-body v0.4.6
   Compiling string_cache_codegen v0.5.2
   Compiling encoding_rs v0.8.33
   Compiling precomputed-hash v0.1.1
   Compiling mac v0.1.1
   Compiling httpdate v1.0.3
   Compiling tower-service v0.3.2
   Compiling ryu v1.0.17
   Compiling temp-dir v0.1.12
   Compiling lazy_static v1.4.0
   Compiling serde_json v1.0.114
   Compiling gettext-sys v0.21.3
   Compiling markup5ever v0.11.0
   Compiling futf v0.1.5
   Compiling parking_lot v0.12.1
   Compiling url v2.5.0
   Compiling flate2 v1.0.28
   Compiling alpm v3.0.4 (https://github.com/archlinux/alpm.rs?rev=306342#306342ef)
   Compiling serde_derive v1.0.197
   Compiling tokio-macros v2.2.0
   Compiling futures-macro v0.3.30
   Compiling tokio v1.36.0
   Compiling openssl-macros v0.1.1
   Compiling futures-util v0.3.30
   Compiling regex v1.10.3
   Compiling thiserror-impl v1.0.58
   Compiling phf_macros v0.11.2
   Compiling phf v0.10.1
   Compiling async-trait v0.1.77
   Compiling utf-8 v0.7.6
   Compiling unicode-width v0.1.11
   Compiling either v1.10.0
   Compiling version_check v0.9.4
   Compiling rustix v0.38.31
   Compiling base64 v0.21.7
   Compiling dtoa v1.0.9
   Compiling dtoa-short v0.3.4
   Compiling rustls-pemfile v1.0.4
   Compiling ahash v0.8.11
   Compiling tendril v0.4.3
   Compiling html5ever v0.26.0
   Compiling phf v0.11.2
error: failed to run custom build command for `alpm v3.0.4 (https://github.com/archlinux/alpm.rs?rev=306342#306342ef)`

Caused by:
  process didn't exit successfully: `/home/matheus/Downloads/paru/src/paru-2.0.3/target/release/build/alpm-fe8130be9696cf00/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/matheus/.local/share/cargo/git/checkouts/alpm.rs-a0070a235cf20bfa/306342e/alpm/build.rs:25:13:
  this version of alpm.rs does not support libalpm v15.0.0 only v14.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by samuelcordero** [comment] 2024-09-14 13:15
@Spixmaster 
As the guy before you posted, you need to run a symlink in order to trick the rust compiler into thinking its libalpm v14 and not v15. Read the error, understand it, and read what was posted before.

**Comment by ArielHorwitz** [comment] 2024-09-14 13:20
@samuelcordero
I can confirm I created the symlink and tried to rebuild and get the same error. I am assuming the symlink works for an already-built paru but not for building paru. (While trying to fix this in my case, I also tried reinstalling paru before finding this thread)

**Comment by Lunarequest** [comment] 2024-09-14 13:21
hi, I found installing `paru-git` works you could try and build paru-git and then use paru-git to build stable if you need it

**Comment by C0rn3j** [comment] 2024-09-14 14:02
> Temporary workaround - create a symlink for now until there's an update.
> 
> sudo ln -s /usr/lib/libalpm.so.15.0.0 /usr/lib/libalpm.so.14
> 
> Worked for me, and I'll just remove the symlink when it's not needed anymore

Don't symlink different SO libraries for something that handles your system files, a package manager is the last thing you want to break on undefined behavior, the SO bump happened for a reason.

Build from master as mentioned if you absolutely can't wait for a release.

**Comment by Spixmaster** [comment] 2024-09-14 14:48
> @Spixmaster As the guy before you posted, you need to run a symlink in order to trick the rust compiler into thinking its libalpm v14 and not v15. Read the error, understand it, and read what was posted before. 😉

Your mentioned solution does not state whether it applies to running the executable or building.

**Comment by ndavd** [comment] 2024-09-14 14:58
> Build from master as mentioned if you absolutely can't wait for a release.

+1. Just do:
```
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru-git.git
cd paru-git
makepkg -si
```
Once this issue is resolved you may go back and install `paru` the regular way.

**Comment by shurizzle** [comment] 2024-09-14 16:52
```bash
(which patchelf >/dev/null 2>/dev/null || sudo pacman -S --asdeps patchelf) && patchelf --replace-needed libalpm.so.14 libalpm.so.15 "$(which paru)" && paru -c && yes | paru -Scc
```

**Comment by kescherCode** [comment] 2024-09-14 17:13
@shurizzle your solution has the same issues as the symlink: It ends up using a library it was not explicitly linked against and that intentionally had an soname bump due to incompatibility reasons.

**Comment by shurizzle** [comment] 2024-09-14 17:48
> @shurizzle your solution has the same issues as the symlink: It ends up using a library it was not explicitly linked against and that intentionally had an soname bump due to incompatibility reasons.

In general you are totally right but it works to reinstall itself from master.

**Comment by anotherglitchinthematrix** [comment] 2024-09-14 18:03
> hi, I found installing `paru-git` works you could try and build paru-git and then use paru-git to build stable if you need it

Took ages to build rust :^) but a working solution for sure.

**Comment by kj-sh604** [comment] 2024-09-15 07:07
cross-posting my comment from [#1240](https://github.com/Morganamilo/paru/issues/1240#issuecomment-2351421609):

<br>

I re-wrote the `paru-git` PKGBUILD, and I think it could be useful for some folks. Essentially, it builds the latest paru git commit into a regular `paru` release package instead of a `paru-git` package. That way, when the official `paru` package eventually gets updated, you'll automatically get the latest release without having to remember to remove `paru-git`. It's admittedly a bit of a quick janky re-write 😅 (I promise my AUR PKGBUILDs are much cleaner 😆), but I think it could be a decent temporary fix for some people.

```
pkgname=paru
_pkgname=paru
pkgver=2.0.3
pkgrel=1
pkgdesc='Feature packed AUR helper'
url='https://github.com/morganamilo/paru'
source=("git+https://github.com/morganamilo/paru")
backup=("etc/paru.conf")
arch=('i686' 'pentium4' 'x86_64' 'arm' 'armv7h' 'armv6h' 'aarch64')
license=('GPL-3.0-or-later')
makedepends=('cargo')
depends=('git' 'pacman' 'libalpm.so>=14')
optdepends=('bat: colored pkgbuild printing' 'devtools: build in chroot and downloading pkgbuilds')
conflicts=('paru-git')
provides=('paru')
sha256sums=(SKIP)

prepare() {
  cd "$_pkgname"
  cargo fetch --locked --target "$(rustc -vV | sed -n 's|host: ||p')"
}

build () {
  cd "$srcdir/$_pkgname"

  if pacman -T pacman-git > /dev/null; then
    _features+="git,"
  fi

  if [[ $(rustc -V) == *"nightly"* ]]; then
    _features+="backtrace,"
  fi

  if [[ $CARCH != x86_64 ]]; then
    export CARGO_PROFILE_RELEASE_LTO=off
  fi

  PARU_VERSION=$pkgver cargo build --frozen --features "${_features:-}" --release --target-dir target
  ./scripts/mkmo locale/
}

package() {
  cd "$srcdir/$_pkgname"

  install -Dm755 target/release/paru "${pkgdir}/usr/bin/paru"
  install -Dm644 paru.conf "${pkgdir}/etc/paru.conf"

  install -Dm644 man/paru.8 "$pkgdir/usr/share/man/man8/paru.8"
  install -Dm644 man/paru.conf.5 "$pkgdir/usr/share/man/man5/paru.conf.5"

  install -Dm644 completions/bash "${pkgdir}/usr/share/bash-completion/completions/paru.bash"
  install -Dm644 completions/fish "${pkgdir}/usr/share/fish/vendor_completions.d/paru.fish"
  install -Dm644 completions/zsh "${pkgdir}/usr/share/zsh/site-functions/_paru"

  install -d "$pkgdir/usr/share/"
  cp -r locale "$pkgdir/usr/share/"
}
```

**Comment by frazar** [comment] 2024-09-15 11:48
This class of build issues has also happened in the past when pacman has bumped the version of the `libalpm.so` library.

To avoid this in the future, would it be possible to pin the `PKGBUILD` to a specific version of `libalpm.so` or `pacman`?

For example, take the `PKGBUILD` draft proposed by @TheGentleChainsaw (thanks!). Would the following change help ensure that no breakage occurs if (or when) `libalpm.so.16` is published in the future?

```diff
-depends=('git' 'pacman' 'libalpm.so>=15')
+depends=('git' 'pacman' 'libalpm.so=15')
```

**Comment by TheBill2001** [comment] 2024-09-15 18:15
@frazar I think doing that would prevent you from update pacman at all in the future.

If I'm right, paru resolves dependencies of repos packages, install them, and then does the same with AUR ones after, but separate. As in, paru does not resolve dependencies of new AUR packages at the same time as the ones from repos (? - correct me on this). So when there is an update for pacman with `libalpm.so.16`, paru will refuse to update because of dependency conflict. This is because, in this case, the already installed paru requires an older version of the library.

I guess it could prevent paru from becoming unusable. You could still update other packages that are not pacman.

**Comment by jm355** [comment] 2024-09-15 18:28
A deeper change would be to update paru to notice this case, and warn the user that it's holding back the pacman update until paru is updated to handle it

**Comment by frazar** [comment] 2024-09-16 07:34
@TheBill2001 You are right. Updates of `pacman` would be prevented if the `libalpm.so=15` dependency is used instead of `libalpm.so>=15`. But I still think it's the best of the two solutions.

Consider the case where the `libalpm.so` library is pinned to version 15 in the `PKGBUILD` and an update to version 16 is released in a `pacman` update. The user would have to perform these steps to update both `paru` and `pacman`:

- uninstall `paru`
- update `pacman`
- install compatible `paru` version "manually" from PKGBUILD

However, I would argue that the same steps are anyway required in the scenario with `libalpm.so>=15` dependency specified in the `PKBUILD`. Indeed, since the `pacman` update is not prevented, it results in a broken `paru` installation, where any invocation results in a panic:

```
paru: error while loading shared libraries: libalpm.so.15: cannot open shared object file: No such file or directory
```

And even in this case, fixing the installation requires the same steps mentioned above, with two additional disadvantages:

1. The error message (`paru: error while loading shared libraries ...`) shown to the user can not be controlled (_e.g._, to provide helpful information on the root cause and solution). Instead, with `libalpm.so=15`, `paru` is fully functional and can inform the user of the prevented update and of the manual steps required.
2. Unless a new `paru` release is immediately available, the `paru` installation will stay broken (unless extra manual steps are performed to downgrade pacman). Instead, with `libalpm.so=15`, `paru` is fully functional.

**Comment by XxTriviumxX** [comment] 2024-09-16 13:55
is the paru dev even aware of this?

**Comment by 1Naim** [comment] 2024-09-16 16:46
> is the paru dev even aware of this?

Not sure but you can check https://github.com/Morganamilo/paru/commit/90656a901479b77cb3b7a54e393dff9a0ca6a45f and https://github.com/archlinux/alpm.rs/commit/65a14f279c2be78d889cbb631a09ad82c706aeae

**Comment by Masero11** [comment] 2024-09-17 03:40
Hello creator of paru this is probably my first coment ever here on github I just wanted to ask if you are going to eventually merge the current version of paru-git with normal paru to fix the recent problems thank you so much in advance and sorry if I said something dumb I'm a beginner in linux and this things

**Comment by Masero11** [comment] 2024-09-17 03:41
> Hello creator of paru this is probably my first coment ever here on github I just wanted to ask if you are going to eventually merge the current version of paru-git with normal paru to fix the recent problems thank you so much in advance and sorry if I said something dumb I'm a beginner in linux and this things

I forgot to add I use arch btw

**Comment by xlacroixx** [comment] 2024-09-17 21:31
> I forgot to add I use arch btw xd

23 dislikes and counting. That's the Linux community for ya.

**Comment by developomp** [comment] 2024-09-18 02:31
I normally don't like it when people create noise on other people's repo while everyone else is trying to solve a problem, but the bug has been pretty much solved in this case and there's only going to be Linux drama from this point onward, so I'll take this opportunity to reiterate an important distinction inexperienced GH users always seem to forget:

"Github is not a forum".

I'm sorry for adding negativity and potentially adding fuel to the drama, but I hope this helps more people in the long run.

And for everyone else, please understand that people rarely comment with the intention to create noise and derail the conversation. Most "dumb" comments are made by regular people who just lacks the understanding of the way people collaborate on a project.

We all make mistakes and I'm pretty sure everyone has made a bug report something along the lines of "This feature doesn't work and I use Windows 10 with 16GB RAM".

The Linux community is notoriously bad at raising new members, but if we just tune things down a bit and nudge them in the right direction, I think we'll see more people making meaningful contributions.

Also, hi Brodie!

**Comment by Masero11** [comment] 2024-09-18 11:58
Thanks for the explanation

**Comment by itaranto** [comment] 2024-09-18 13:38
> > I forgot to add I use arch btw xd
> 
> 23 dislikes and counting. That's the Linux community for ya.

It's being disliked because it's appropriate nor relevant to a techincal discussion in a GH issue.

I enjoy the joke myself, but I prefer to see those on Reddit or some other places.

**Comment by DHDcc** [comment] 2024-09-18 14:37
> > > I forgot to add I use arch btw xd
> > 
> > 
> > 23 dislikes and counting. That's the Linux community for ya.
> 
> It's being disliked because it's appropriate nor relevant for a technical discussion in a GH issue.
> 
> I enjoy the joke myself, but I prefer to see those on Reddit or some other places.

agreed

**Comment by parham-dev27** [comment] 2024-09-18 19:39
Not a fix but a temporary workaround. 
`sudo patchelf --replace-needed libalpm.so.14 libalpm.so.15 "$(which paru)"`
This updates the paru executable to use the newer version of the libalpm

**Comment by furrykef** [comment] 2024-09-19 02:44
That workaround was already mentioned above:

> This solution patches the executable instead of linking libs that you'll forget to delete
> 
> ```shell
> (which patchelf >/dev/null 2>/dev/null || sudo pacman -S --asdeps patchelf) && sudo patchelf --replace-needed libalpm.so.14 libalpm.so.15 "$(which paru)" && paru -c && yes | paru -Scc
> ```

To which kescherCode replied:

> @shurizzle your solution has the same issues as the symlink: It ends up using a library it was not explicitly linked against and that intentionally had an soname bump due to incompatibility reasons.

**Comment by se7en-x230** [comment] 2024-09-19 03:22
So you recommend to wait for an official fix?

**Comment by RealStickman** [comment] 2024-09-19 04:23
> So you recommend to wait for an official fix?

You could use this git version PKGBUILD, which will upgrade with the normal `paru` package once a new release comes out.

https://github.com/Morganamilo/paru/issues/1239#issuecomment-2351465944

**Comment by Spixmaster** [comment] 2024-09-19 07:04
The file `/usr/lib/debug/usr/bin/paru.debug` already exists. That is why the content of the new package cannot be copied to that destination. Do `sudo pacman -Rsn paru` and in case that errors still happen, delete the conflicting files manually.

**Comment by furrykef** [comment] 2024-09-19 22:11
@Morganamilo Please forgive the ping, but I just want to make sure that you're aware that the paru and paru-bin packages have been unusable since the 14th. There are workarounds, but as seen in this thread, some people are using workarounds that are not correct, such as symlinking the .so file or patching the executable to load the new .so file. Instead of waiting for a new full release, I think it would be best to make a quick fork of 2.0.3 that fixes this issue and nothing else.

**Comment by furrykef** [comment] 2024-09-20 05:49
I see that the package has been updated and appears to be working fine for me. Thanks! 🙂

**Comment by kescherCode** [comment] 2024-09-20 08:51
This issue should be closed.

**Comment by Leuchak** [comment] 2024-09-20 13:18
I still have this:
> error: failed to run custom build command for `alpm v3.0.4 (https://github.com/archlinux/alpm.rs?rev=306342#306342ef)`
>
> Caused by: 
 process didn't exit successfully: `/mnt/gamedata/makepkg/paru/src/paru-2.0.3/target/release/build/alpm-a6f501ad50f6c328/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/leuchak/.cargo/git/checkouts/alpm.rs-a0070a235cf20bfa/306342e/alpm/build.rs:25:13:
  this version of alpm.rs does not support libalpm v15.0.0 only v14.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  
  
  I did `git pull`
  cargo run

**Comment by kescherCode** [comment] 2024-09-20 13:21
@Leuchak you're trying to build 2.0.3. https://aur.archlinux.org/packages/paru, and releases on the GitHub repo, clearly shows 2.0.4 being released, which resolves this issue.

**Comment by Leuchak** [comment] 2024-09-20 13:26
oh, i dont known why git pull didn't upgrade to 2.0.4.
using [`https://aur.archlinux.org/paru.git`](https://aur.archlinux.org/paru.git) with `makepkg -si` does work

**Comment by tyressk** [comment] 2024-09-23 14:05
> The file `/usr/lib/debug/usr/bin/paru.debug` already exists. That is why the content of the new package cannot be copied to that destination. Do `sudo pacman -Rsn paru` and in case that errors still happen, delete the conflicting files manually.

I had this issue and did `sudo pacman -Rsn paru-debug` to remove paru.debug, didn't need to delete anything manually

**Comment by BacaR00T** [comment] 2024-09-28 11:16
this helped me 
`bacar00t@arch ~ [1]> sudo pacman --version

 .--.                  Pacman v7.0.0 - libalpm v15.0.0
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2024 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       This program may be freely redistributed under
                       the terms of the GNU General Public License.
`
and then 
`sudo ln -s /usr/lib/libalpm.so.15.0.0 /usr/lib/libalpm.so.14`

**Comment by megascrapper** [comment] 2024-09-28 12:29
> this helped me `sudo pacman --version` and then `sudo ln -s /usr/lib/libalpm.so.15.0.0 /usr/lib/libalpm.so.14`

Please see [this comment](https://github.com/Morganamilo/paru/issues/1239#issuecomment-2351003006) on why this is a very bad idea. The proper way to fix this is to first do a full system upgrade with `sudo pacman -Syu` and then rebuild paru manually. I found the latest commit from the [AUR repo](https://aur.archlinux.org/packages/paru) to work just fine.

**Comment by brooksvb** [comment] 2024-10-26 18:30
None of the above solutions work for me.

If I try to `makepkg` with paru.git, I get
```
error: failed to run custom build command for `alpm v4.0.1`

Caused by:
  process didn't exit successfully: `/var/makepkg/build/paru/src/paru/target/release/build/alpm-20dd7cd234a1997d/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/brooksvb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alpm-4.0.1/build.rs:25:13:
  this version of alpm.rs does not support libalpm v14.0.0 only v15.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
```

If I change the PKGBUILD to force libalpm=15, I get
```
==> Making package: paru 2.0.3-1 (Sat 26 Oct 2024 11:23:08 AM MST)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: libalpm.so=15
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> libalpm.so=15
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
```

**Comment by BBaoVanC** [comment] 2024-10-26 20:28
@brooksvb what pacman version is installed? And have you done `git pull` (or newly cloned) recently on the paru-git repo?

**Comment by brooksvb** [comment] 2024-10-27 02:23
@BBaoVanC 
Pacman v6.1.0 - libalpm v14.0.0
My results were done with a fresh git clone

**Closed** 2024-11-15 11:29 UTC

**Comment by Tashar02** [comment] 2024-12-11 16:20
> None of the above solutions work for me.
> 
> If I try to `makepkg` with paru.git, I get
> 
> ```
> error: failed to run custom build command for `alpm v4.0.1`
> 
> Caused by:
>   process didn't exit successfully: `/var/makepkg/build/paru/src/paru/target/release/build/alpm-20dd7cd234a1997d/build-script-build` (exit status: 101)
>   --- stderr
>   thread 'main' panicked at /home/brooksvb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alpm-4.0.1/build.rs:25:13:
>   this version of alpm.rs does not support libalpm v14.0.0 only v15.x.x is supported
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> warning: build failed, waiting for other jobs to finish...
> ==> ERROR: A failure occurred in build().
> ```
> 
> If I change the PKGBUILD to force libalpm=15, I get
> 
> ```
> ==> Making package: paru 2.0.3-1 (Sat 26 Oct 2024 11:23:08 AM MST)
> ==> Checking runtime dependencies...
> ==> Installing missing dependencies...
> error: target not found: libalpm.so=15
> ==> ERROR: 'pacman' failed to install missing dependencies.
> ==> Missing dependencies:
>   -> libalpm.so=15
> ==> Checking buildtime dependencies...
> ==> ERROR: Could not resolve all dependencies.
> ```

Can confirm I am also getting the same error.

**Comment by brooksvb** [comment] 2024-12-12 01:31
For what it's worth, I eventually solved my issues with updating paru by discovering that my mirrors were messed up. I used [rate-mirrors](https://github.com/westandskif/rate-mirrors) to update my mirrors, got all my system packages up to date, and was able to fix everything else after that. Just make sure you are actually saving the mirror list and not just outputting to stdout
