### ISSUE TITLE
[Bug] PKGBUILD review only shows filename inside the package folder

### ISSUE THREAD

**Issue by leapofazzam123** [Morganamilo/paru#284] opened 2021-03-18 06:26 UTC
### Affected Version
**paru -V**
```
paru v1.4.0 - libalpm v12.0.2
```

### Step to reproduce
1. Install a package with paru
2. Review the package PKGBUILD

### Expected result
It should display the content of PKGBUILD file

![Screenshot_20210318-131934](https://user-images.githubusercontent.com/76893443/111582295-33251800-87ed-11eb-8ffa-9ea24f71078c.png)

### Actual result
It display the filename of the PKGBUILD, not the content. Not only PKGBUILD file name is displayed, but also other files in the package directory

![Screenshot_20210318-131857](https://user-images.githubusercontent.com/76893443/111582503-7e3f2b00-87ed-11eb-9e55-ad83a688cfd4.png)

**Comment by Morganamilo** [comment] 2021-03-18 13:29
Weird. Are those regular files? Do you have any bat flags set?

**Comment by LeapofAzzam-backup** [comment] 2021-03-19 13:56
No, i didn't set any custom bat flags or anything. And these are regular
files

Pada tanggal Kam, 18 Mar 2021 8.29 PM, Lulu ***@***.***>
menulis:

**Comment by Morganamilo** [comment] 2021-03-20 00:08
Can't reproduce. Even trying snapd. Is this reproducable? is it just this package or others too? You can delete the package files from cache to reset it to unreviewed.

**Comment by LeapofAzzam-backup** [comment] 2021-03-20 02:38
Yes, its also in other AUR packages, so not only snapd.

Pada tanggal Sab, 20 Mar 2021 7.08 AM, Lulu ***@***.***>
menulis:

**Comment by LeapofAzzam-backup** [comment] 2021-04-22 10:51
No response 😐

**Comment by Morganamilo** [comment] 2021-04-22 10:58
That's cause I have no way to reproduce.

**Comment by Morganamilo** [comment] 2021-06-13 10:57
Nobody else seems to have this. Plus there's been plenty of fixes in the devel code that maybe this fixed itself. Closing as not reproducible.

**Closed by Morganamilo** 2021-06-13 10:57 UTC
