### ISSUE TITLE
google-chrome-dev reinstalls on every update

### ISSUE THREAD

**Issue by frogtd** [Morganamilo/paru#218] opened 2021-02-05 03:54 UTC
What the title says. I would guess it is because it has another provider for google-chrome (google-chrome) so when you select one of them it installs that one.
```
...
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: Resolving dependencies...
:: There are 2 providers available for google-chrome:
:: Repository AUR:
    1) google-chrome  2) google-chrome-dev
Enter a number (default=1): 2
:: Calculating conflicts...
:: Calculating inner conflicts...
:: Packages not in the AUR: python2-css-parser  python2-html2text  python2-html5-parser  python2-netifaces
    python2-pychm  python2-pyqt5  python2-pyqtwebengine  python2-sip-pyqt5  python2-unrardll

Aur (1) google-chrome-dev-90.0.4400.8-1

:: Proceed to review? [Y/n]:

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
:: Proceed with installation? [Y/n]: n
```

**Comment by Morganamilo** [comment] 2021-02-05 10:05
What package do you actually have installed? The normal or the dev?

**Comment by frogtd** [comment] 2021-02-05 13:46
The dev package.

**Comment by Morganamilo** [comment] 2021-02-05 13:50
Wierd, I guess a package is pulling it in as a dep and paru think's it's not satisfied? What does `pacman -Qii google-chrome-dev` show?

**Comment by frogtd** [comment] 2021-02-06 02:33
```
Name            : google-chrome-dev
Version         : 90.0.4408.0-1
Description     : The popular and trusted web browser by Google (Dev Channel)
Architecture    : x86_64
URL             : https://www.google.com/chrome
Licenses        : custom:chrome
Groups          : None
Provides        : google-chrome
Depends On      : alsa-lib  gtk3  libcups  libxss  libxtst  nss
Optional Deps   : libpipewire02: WebRTC desktop sharing under Wayland
                  kdialog: for file dialogs in KDE
                  gnome-keyring: for storing passwords in GNOME keyring [installed]
                  kwallet: for storing passwords in KWallet [installed]
                  gtk3-print-backends: for printing [installed]
                  libunity: for download progress on KDE
                  ttf-liberation: fix fonts for some PDFs - CRBug #369991 [installed]
                  xdg-utils [installed]
Required By     : None
Optional For    : chromedriver
Conflicts With  : None
Replaces        : None
Installed Size  : 251.86 MiB
Packager        : Unknown Packager
Build Date      : Fri Feb 5 21:32:11 2021
Install Date    : Fri Feb 5 21:32:21 2021
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
Backup Files    :
(none)
```

**Comment by Morganamilo** [comment] 2021-02-14 21:25
Looking at the output closer `Aur (1) google-chrome-dev-90.0.4400.8-1`. The aur's version is `90.0.4400.8-1` yet your local version is `90.0.4408.0-1`.

Not sure why that is. Did you update the pkgbuild yourself? Or maybe they forgot to update the srcinfo.

Still paru shouldn't be trying to downgrade the package. Unless you were using -uu.

**Comment by frogtd** [comment] 2021-02-14 22:36
I wasn't and even now, when both versions match, it still prompts a reinstall.

**Comment by Morganamilo** [comment] 2021-02-15 20:04
Can't reproduce so there's not much I can do.

**Comment by Morganamilo** [comment] 2021-06-13 10:50
Nobody else seems to have this. Plus there's been plenty of fixes in the devel code that maybe this fixed itself. Closing as not reproducible.

**Closed by Morganamilo** 2021-06-13 10:50 UTC
Labels: bug
