### ISSUE TITLE
paru itself fails to compile

### ISSUE THREAD

**Issue by pericles256** [Morganamilo/paru#1281] opened 2024-11-27 00:59 UTC
### Affected Version
**paru -V**
current version 2.0.4

### Description
**Have you checked previous issues?**
Yes, I did not see this issue. I was using the install paru steps listed on github. I am using the arm version of Arch linux on a Radza Rock-5b. The installed failed while executing the makepkg -si step.  I have built wezterm from source on this system.  That means the rust toolchain is working. 

### Output
**Include the FULL output of any relevant commands/configs**
See attached file
[paru-makepkg.txt](https://github.com/user-attachments/files/17927082/paru-makepkg.txt)

**paru.conf and pacman.conf are usually always relevant**
There is not a paru.conf file as it has not been installed.

```sh
If this is asking what shell I am using it is zsh but I also tried it with bash.  Same result.
```

**Comment by nPHYN1T3** [comment] 2024-11-28 23:37
I'm seeing a build fail on 2.0.4 as well but my logs are much different.

Highlights are simply paru lib generated 2 warnings which immediately becomes could not compile paru (caused by) process didn't exit successfully. (cue long rust line I can't copy from VM terminal)

**Comment by romanstingler** [comment] 2024-12-15 23:39
is this still a thing ??

**Comment by pericles256** [comment] 2024-12-18 18:52
Yes , it still fails. I just rerun the build with the following results:
> git clone https://aur.archlinux.org/paru.git  
  Cloning into 'paru'...
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
remote: Enumerating objects: 188, done.
remote: Counting objects: 100% (188/188), done.
remote: Compressing objects: 100% (132/132), done.
remote: Total 188 (delta 57), reused 187 (delta 56), pack-reused 0 (from 0)
Receiving objects: 100% (188/188), 59.81 KiB | 338.00 KiB/s, done.
Resolving deltas: 100% (57/57), done.
┌─(~/aur)────────────────────────────────────────────────────────────────────────────────────────────────────(perryw@rock-5b:pts/2)─┐
└─(11:45:18)──> cd paru                                                                                               ──(Wed,Dec18)─┘
┌─(~/aur/paru)───────────────────────────────────────────────────────────────────────────────────────────────(perryw@rock-5b:pts/2)─┐
└─(11:46:58)──> makepkg -si                                                                                           ──(Wed,Dec18)─┘
==> Making package: paru 2.0.4-1 (Wed Dec 18 11:47:10 2024)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading paru-2.0.4.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 8064k    0 8064k    0     0  2469k      0 --:--:--  0:00:03 --:--:-- 2848k
==> Validating source files with sha256sums...
    paru-2.0.4.tar.gz ... Passed
==> Extracting sources...
  -> Extracting paru-2.0.4.tar.gz with bsdtar
==> Starting prepare()...
warning: Patch `alpm v3.0.4 (https://github.com/archlinux/alpm.rs?rev=306342#306342ef)` was not used in the crate graph.
Patch `aur-depends v3.0.0 (https://github.com/Morganamilo/aur-depends?rev=30c2c1#30c2c150)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
==> Starting build()...
warning: Patch `alpm v3.0.4 (https://github.com/archlinux/alpm.rs?rev=306342#306342ef)` was not used in the crate graph.
Patch `aur-depends v3.0.0 (https://github.com/Morganamilo/aur-depends?rev=30c2c1#30c2c150)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.13
   Compiling libc v0.2.158
   Compiling memchr v2.7.4
   Compiling autocfg v1.3.0
   Compiling cfg-if v1.0.0
   Compiling pkg-config v0.3.30
   Compiling byteorder v1.5.0
   Compiling shlex v1.3.0
   Compiling siphasher v0.3.11
   Compiling cc v1.1.21
   Compiling once_cell v1.19.0
   Compiling pin-project-lite v0.2.14
   Compiling serde v1.0.210
   Compiling quote v1.0.37
   Compiling bitflags v2.6.0
   Compiling log v0.4.22
   Compiling syn v2.0.77
   Compiling itoa v1.0.11
   Compiling getrandom v0.2.15
   Compiling futures-core v0.3.30
   Compiling bytes v1.7.2
   Compiling rand_core v0.6.4
   Compiling slab v0.4.9
   Compiling futures-sink v0.3.30
   Compiling vcpkg v0.2.15
   Compiling phf_shared v0.10.0
   Compiling phf_shared v0.11.2
   Compiling futures-channel v0.3.30
   Compiling futures-task v0.3.30
   Compiling futures-io v0.3.30
   Compiling pin-utils v0.1.0
   Compiling alpm-sys v4.0.0
   Compiling equivalent v1.0.1
   Compiling hashbrown v0.14.5
   Compiling aho-corasick v1.1.3
   Compiling crossbeam-utils v0.8.20
   Compiling openssl v0.10.66
   Compiling foreign-types-shared v0.1.1
   Compiling fnv v1.0.7
   Compiling adler2 v2.0.0
   Compiling signal-hook-registry v1.4.2
   Compiling socket2 v0.5.7
   Compiling mio v1.0.2
   Compiling indexmap v2.5.0
   Compiling smallvec v1.13.2
   Compiling openssl-sys v0.9.103
   Compiling regex-syntax v0.8.4
   Compiling tinyvec_macros v0.1.1
   Compiling tinyvec v1.8.0
   Compiling miniz_oxide v0.8.0
   Compiling http v0.2.12
   Compiling foreign-types v0.3.2
   Compiling tracing-core v0.1.32
   Compiling lock_api v0.4.12
   Compiling httparse v1.9.4
   Compiling percent-encoding v2.3.1
   Compiling new_debug_unreachable v1.0.6
   Compiling parking_lot_core v0.9.10
   Compiling native-tls v0.2.12
   Compiling form_urlencoded v1.2.1
   Compiling unicode-normalization v0.1.24
   Compiling tracing v0.1.40
   Compiling unicode-bidi v0.3.15
   Compiling try-lock v0.2.5
   Compiling thiserror v1.0.63
   Compiling scopeguard v1.2.0
   Compiling openssl-probe v0.1.5
   Compiling idna v0.5.0
   Compiling want v0.3.1
   Compiling http-body v0.4.6
   Compiling regex-automata v0.4.7
   Compiling crc32fast v1.4.2
   Compiling encoding_rs v0.8.34
   Compiling lazy_static v1.5.0
   Compiling temp-dir v0.1.13
   Compiling mac v0.1.1
   Compiling httpdate v1.0.3
   Compiling serde_json v1.0.128
   Compiling zerocopy-derive v0.7.35
   Compiling serde_derive v1.0.210
   Compiling tokio-macros v2.4.0
   Compiling futures-macro v0.3.30
   Compiling zerocopy v0.7.35
   Compiling tokio v1.40.0
   Compiling futures-util v0.3.30
   Compiling openssl-macros v0.1.1
   Compiling ppv-lite86 v0.2.20
   Compiling rand_chacha v0.3.1
   Compiling rand v0.8.5
   Compiling phf_generator v0.10.0
   Compiling phf_generator v0.11.2
   Compiling phf_macros v0.11.2
   Compiling phf_codegen v0.11.2
   Compiling string_cache_codegen v0.5.2
   Compiling regex v1.10.6
   Compiling phf v0.11.2
   Compiling thiserror-impl v1.0.63
   Compiling ryu v1.0.18
   Compiling tokio-util v0.7.12
   Compiling h2 v0.3.26
   Compiling precomputed-hash v0.1.1
   Compiling tower-service v0.3.3
   Compiling tokio-native-tls v0.3.1
   Compiling markup5ever v0.12.1
   Compiling phf_codegen v0.10.0
   Compiling url v2.5.2
   Compiling futf v0.1.5
   Compiling gettext-sys v0.21.4
   Compiling flate2 v1.0.33
   Compiling parking_lot v0.12.3
   Compiling alpm v4.0.1
   Compiling version_check v0.9.5
   Compiling utf-8 v0.7.6
   Compiling dtoa v1.0.9
   Compiling either v1.13.0
   Compiling unicode-width v0.1.14
   Compiling base64 v0.21.7
   Compiling rustix v0.38.37
   Compiling rustls-pemfile v1.0.4
   Compiling tokio-socks v0.5.2
   Compiling ahash v0.8.11
   Compiling dtoa-short v0.3.5
   Compiling string_cache v0.8.7
   Compiling tendril v0.4.3
   Compiling async-compression v0.4.12
   Compiling selectors v0.25.0
   Compiling serde_urlencoded v0.7.1
   Compiling html5ever v0.27.0
   Compiling cssparser-macros v0.6.1
   Compiling crossbeam-epoch v0.9.18
   Compiling num-traits v0.2.19
   Compiling utf8parse v0.2.2
   Compiling mime v0.3.17
   Compiling cfg_aliases v0.1.1
   Compiling ipnet v2.10.0
   Compiling cini v1.0.0
   Compiling stable_deref_trait v1.2.0
   Compiling gimli v0.31.0
   Compiling sync_wrapper v0.1.2
   Compiling linux-raw-sys v0.4.14
   Compiling portable-atomic v1.7.0
   Compiling fxhash v0.2.1
   Compiling servo_arc v0.3.0
   Compiling pacmanconf v3.0.0
   Compiling crossbeam-deque v0.8.5
   Compiling nix v0.28.0
   Compiling anstyle-parse v0.2.5
   Compiling cssparser v0.31.2
   Compiling hyper v0.14.30
   Compiling addr2line v0.24.1
error[E0308]: mismatched types
   --> /home/perryw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alpm-4.0.1/src/cb.rs:244:60
    |
244 |         unsafe { alpm_option_set_logcb(self.as_ptr(), Some(cb), &*ctx as *const _ as *mut _) };
    |                                                       ---- ^^ expected fn pointer, found fn item
    |                                                       |
    |                                                       arguments to this enum variant are incorrect
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _, _, *mut __va_list_tag)`
                  found fn item `extern "C" fn(_, _, _, [__va_list_tag; 1]) {logcb::<LogCbImpl<T, F>>}`
help: the type constructed contains `extern "C" fn(*mut c_void, u32, *const u8, [__va_list_tag; 1]) {logcb::<LogCbImpl<T, F>>}` due to the type of the argument passed
   --> /home/perryw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alpm-4.0.1/src/cb.rs:244:55
    |
244 |         unsafe { alpm_option_set_logcb(self.as_ptr(), Some(cb), &*ctx as *const _ as *mut _) };
    |                                                       ^^^^^--^
    |                                                            |
    |                                                            this argument influences the type of `Some`
note: tuple variant defined here
   --> /home/perryw/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:579:5
    |
579 |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
    |     ^^^^

   Compiling serde_spanned v0.6.7
For more information about this error, try `rustc --explain E0308`.
error: could not compile `alpm` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by Morganamilo** [comment] 2024-12-27 04:37
Current version doesn't like arm. See https://github.com/Morganamilo/paru/issues/1154

It's fixed in git so either use paru-git or modify the pkgbuild to use the generate feature as shown in the above issue.

**Closed by Morganamilo** 2024-12-27 04:37 UTC
