### ISSUE TITLE
paru -Suy does not "stick"

### ISSUE THREAD

**Issue by fuzebox1** [Morganamilo/paru#170] opened 2021-01-21 07:34 UTC
When i do a full upgrade with paru -Suy it runs fine, but when i do it next time the same packages and versions are in the list again.
yay does not try to upgrade the same list.

**Comment by Morganamilo** [comment] 2021-01-21 08:55
Can you please show the output of this happening.

**Comment by fuzebox1** [comment] 2021-01-21 23:59
https://asciinema.org/a/RrNEFV3nR447Z2Gx18XuZ4KAa

as you can see at ~30sec and ~2.20m, several packages reappear, and new ones pop up seemingly randomly every few times it runs.

**Comment by Morganamilo** [comment] 2021-01-22 00:42
Probably an issue with the devel info saving. May be fixed in git.

**Comment by fuzebox1** [comment] 2021-01-22 03:50
Ok, so clearing out devel.json manually should be ok?

**Comment by Morganamilo** [comment] 2021-01-22 08:56
It may fix the issue but not the cause. Try the git version as it may be fixed there.

**Comment by Morganamilo** [comment] 2021-01-30 14:15
Gonna assume it's fixed.

**Closed by Morganamilo** 2021-01-30 14:15 UTC

**Comment by fuzebox1** [comment] 2021-01-30 15:57
Yes. I cleared everything out of devel.json. It hasn't repeated itself.
