### ISSUE TITLE
Update -bin (libssl update)

### ISSUE THREAD

**Issue by Rippanda12** [Morganamilo/paru#898] opened 2022-11-19 09:46 UTC
### Affected Version
**paru -V**
Latest (update -bin)
### Description
**Have you checked previous issues?**

### Output

```sh
paru: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by Rippanda12** [comment] 2022-11-19 10:09
NOTE: This happens on aarch64 (ARM) and not on x86

**Comment by jabra11** [comment] 2022-11-20 17:45
happens on x86 aswell for me

**Comment by Morganamilo** [comment] 2022-11-21 01:07
It really shouldn't be happening on x86. Unless you're on manjaro or something which is behind on the update.

**Comment by paramtt** [comment] 2022-11-21 01:50
I believe this should be fixed by `pacman -Syu openssl-1.1`

**Comment by Morganamilo** [comment] 2022-11-21 16:35
Ideally paru would update to use the new version. I may do another rebuild release now that arm has updated.

**Comment by jvdsn** [comment] 2022-11-22 18:05
> Ideally paru would update to use the new version. I may do another rebuild release now that arm has updated.

Ideally, yes. paru-v1.11.2-aarch64.tar.zst seems to contain a binary linked to OpenSSL 1.1.1:
```
$ ldd paru
        linux-vdso.so.1 (0x0000ffff8dba3000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libalpm.so.13 => /usr/lib/libalpm.so.13 (0x0000ffff8d500000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x0000ffff8d4d0000)
        libm.so.6 => /usr/lib/libm.so.6 (0x0000ffff8d420000)
        libc.so.6 => /usr/lib/libc.so.6 (0x0000ffff8d260000)
        libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x0000ffff8cde0000)
        libarchive.so.13 => /usr/lib/libarchive.so.13 (0x0000ffff8cd00000)
        libcurl.so.4 => /usr/lib/libcurl.so.4 (0x0000ffff8cc40000)
        libgpgme.so.11 => /usr/lib/libgpgme.so.11 (0x0000ffff8cbd0000)
        /lib/ld-linux-aarch64.so.1 => /usr/lib/ld-linux-aarch64.so.1 (0x0000ffff8db6a000)
        libacl.so.1 => /usr/lib/libacl.so.1 (0x0000ffff8cbb0000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x0000ffff8cb70000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x0000ffff8cb30000)
        libzstd.so.1 => /usr/lib/libzstd.so.1 (0x0000ffff8ca90000)
        liblz4.so.1 => /usr/lib/liblz4.so.1 (0x0000ffff8ca50000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x0000ffff8ca20000)
        libz.so.1 => /usr/lib/libz.so.1 (0x0000ffff8c9f0000)
        libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0x0000ffff8c9a0000)
        libidn2.so.0 => /usr/lib/libidn2.so.0 (0x0000ffff8c950000)
        libssh2.so.1 => /usr/lib/libssh2.so.1 (0x0000ffff8c8f0000)
        libpsl.so.5 => /usr/lib/libpsl.so.5 (0x0000ffff8c8c0000)
        libssl.so.3 => /usr/lib/libssl.so.3 (0x0000ffff8c7f0000)
        libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x0000ffff8c780000)
        libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x0000ffff8c760000)
        libassuan.so.0 => /usr/lib/libassuan.so.0 (0x0000ffff8c730000)
        libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x0000ffff8c6f0000)
        libunistring.so.5 => /usr/lib/libunistring.so.5 (0x0000ffff8c520000)
        libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x0000ffff8c400000)
        libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x0000ffff8c3b0000)
        libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x0000ffff8c390000)
        libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x0000ffff8c360000)
        libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x0000ffff8c340000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x0000ffff8c310000)
        libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x0000ffff8c2d0000)
```

**Comment by jvdsn** [comment] 2023-02-04 23:16
@Morganamilo any update on this for aarch64?

**Comment by bulletmark** [comment] 2023-05-08 22:43
Occasionally I consider to switch from `yay` to `paru` but then I strike this error on all my ARM boxes and give up immediately. :(

**Comment by lafleurdeboum** [comment] 2023-09-04 10:46
I had the same issue on armv7. Installing `openssl-1.1` worked it around. No clue wether the issue is still pending for aarch64. I can confirm I haven't experienced it on x86_64.

@Morganamilo would you trigger a rebuild for this platform or should we add `openssl-1.1` to the dependencies of paru on armv7 platform ? Not sure if there's platform-specific depends in PKGBUILDs though.

Anyway that didn't stop me from switching from yay :)

**Comment by leonghui** [comment] 2023-11-28 20:05
Managed to resolve this and remove `openssl-1.1` by updating to the new release:
https://github.com/Morganamilo/paru/releases/tag/v2.0.0

**Closed** 2023-12-04 23:57 UTC

**Comment by bjo81** [comment] 2024-04-24 10:03
What's the problem with it? You can rebuild  yourself, the issue can be closed!

**Comment by lnicola** [comment] 2024-04-24 10:08
Why offer binary releases if they don't work?

What's strange, though, is that `paru-bin` works fine, even though it should be the same binary:

```
$ tar xf paru-v2.0.3-x86_64.tar.zst && b2sum paru /usr/bin/paru && paru -Qi paru
7b5768e3b9ba937d3eef587d558e28be326ec7456c0d8cd7d37be8b77a1af6998d7458a2bfa70f6a842af02f87542a86640809ba99dedbe96af89fa45fb8d413  paru
b13d677827ef82a4423c242eb0288513a45a76fd6f32475337dee3527e24043f8969f44c7fa879def07a582cd53074c5d7d8acb57e8fdebb5ddebd39c4626b46  /usr/bin/paru
Name            : paru-bin
Version         : 2.0.3-3
Description     : Feature packed AUR helper
Architecture    : x86_64
URL             : https://github.com/morganamilo/paru
Licenses        : GPL-3.0-or-later
Groups          : None
Provides        : paru
Depends On      : git  pacman  libalpm.so>=14
Optional Deps   : bat: colored pkgbuild printing [installed]
                  devtools: build in chroot and downloading pkgbuilds
Required By     : None
Optional For    : None
Conflicts With  : paru
Replaces        : None
Installed Size  : 8.33 MiB
Packager        : Unknown Packager
Build Date      : Wed 24 Apr 2024 13:06:58 EEST
Install Date    : Wed 24 Apr 2024 13:07:15 EEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

**Comment by lnicola** [comment] 2024-04-24 10:10
Got it, `paru-v2.0.3-1-x86_64.tar.zst` works fine.
