### ISSUE TITLE
invalid "validpgpkeys" does not allow the package to be installed

### ISSUE THREAD

**Issue by mindyourlifeguide** [Morganamilo/paru#335] opened 2021-04-18 21:20 UTC
### Affected Version
**paru -V**
paru v1.5.1 - libalpm v12.0.2

### Description
Prevents installation of a package with incorrect "validpgpkeys".

Installed package xorg-server-bug865 and couldn't install. Immediately gave an error. Didn't offer to edit pkgbuild / don't import keys.

Yay allowed not to import keys and installed the package without any problems.

![image](https://user-images.githubusercontent.com/35348648/115161179-cf6c6400-a0a4-11eb-9b32-873960365488.png)

**Comment by Morganamilo** [comment] 2021-04-18 21:32
The pkgbuild is bad and has an empty key for some reason.

**Comment by mindyourlifeguide** [comment] 2021-04-19 05:29
How do I edit pkgbuild and install the package?
In yay I can edit pkgbuild, I can also not accept all keys

**Comment by Morganamilo** [comment] 2021-04-19 09:31
The issue is the pkgbuild generates an invalid srcinfo. It's the srcinfo file that paru is complaining about. Go bug the maintainer to fix it. I also believe makepkg will refuse this pkgbuild in the next version.

**Comment by mindyourlifeguide** [comment] 2021-04-19 09:36
I can manually edit the PKGBUILD and proceed with the installation.
Why doesn't paru let me do this?
How then does yay solve this problem?

**Comment by Morganamilo** [comment] 2021-04-19 09:39
Like I said the issue is not the pkgbuild but the srcinfo. And as it currently works paru tries to parse them right after downloading.

**Comment by mindyourlifeguide** [comment] 2021-04-19 09:42
That is, through paru this package can not be installed in any way?

**Comment by Morganamilo** [comment] 2021-04-19 09:43
You can edit the srcinfo yourself if you really want to. I don't particularly care to accommodate incorrectly written packages. Plus makepkg will just straight refuse this pkgbuild in the next version, so this issue goes away.

**Comment by mindyourlifeguide** [comment] 2021-04-19 09:47
How can I edit srcinfo via paru?

I'll note that yay installed the package by simply rejecting all the keys, among which just an invalid

**Comment by Morganamilo** [comment] 2021-04-19 09:48
The file is in cache, you can just edit it and commit it.

**Comment by mindyourlifeguide** [comment] 2021-04-19 09:50
Okay, I'll just use yay.

Sadly, hopefully in the future, paru will reach yay functionality.

Thanks for the help!

**Comment by Morganamilo** [comment] 2021-04-19 09:52
Paru will not accept invalid packages and never will. This isn't about reaching yay functionality.

**Comment by mindyourlifeguide** [comment] 2021-04-19 09:55
It's about solving a user's problem - installing a package.
If through one aur helper the user can install the package, but through the other not, then the user's choice is obvious.

No offense to you. I'm just testing paru and giving you feedback on the nuances of use.

**Comment by Morganamilo** [comment] 2021-04-19 09:56
And like I said makepkg will refuse this package in the next version anyway. So then no helper will be able to build it.

**Comment by mindyourlifeguide** [comment] 2021-04-19 09:58
By the way, have you already left the yay project?

I wanted to clarify about [sorting](https://github.com/Jguer/yay/issues/1491).

**Comment by mindyourlifeguide** [comment] 2021-04-19 09:59
_So then no helper will be able to build it._ - this is very sad news, especially for those who will have to install this package later.

**Comment by Morganamilo** [comment] 2021-04-19 10:01
No it's not sad. The maintainer needs to fix their package.

It's like having some invalid json that's missing a closing bracket. And you complain at a json parser for following spec and erroring out when it's missing.

Anyway, makepkg refusing it is a positive not a negative. It means people will notice the issue when making the pkgbuild in the first place, so the broken package will never end up on the aur.

**Comment by mindyourlifeguide** [comment] 2021-04-19 10:03
It's just one of the keys - an empty string.
![image](https://user-images.githubusercontent.com/35348648/115218847-a503c080-a10f-11eb-87fc-b48e5e377279.png)

**Comment by Morganamilo** [comment] 2021-04-19 10:10
Yes, which then generates the line `validpgpkeys = ` in the srcinfo.

In the srcinfo format a blank value means to clear the pkgbases values of this field.

For example:

```
pkgbase = a
	pkgver = 1
	pkgrel = 1
	depends = 1
	depends = 2
	depends = 3

pkgname = a
	depends = 

pkgname = b
```

In this pkgbuild, package b inherits the depends of its pkgbase `1 2 3`, which package a says "clear the dependencies i'm not using any of them".

So it's nonsensical for validpgps to try and clear itself, especially as it can not be overridden like depends can.

**Comment by Morganamilo** [comment] 2021-04-19 10:13
My aproch to aur helpers is to refuse incorrectly made packages to force the maintainer to fix them. While yay's srcinfo parser ignores this specific issue, the parser is still pretty strict for the same reason. In fact I did a whole write up on it here and ended up eliminating a lot of nonsensical packages.

https://github.com/Morganamilo/go-srcinfo/issues/1

**Comment by mindyourlifeguide** [comment] 2021-04-19 10:20
After reading the description of the problem from the link, I understand why paru works this way. Thanks for the annoyance!
I agree that in terms of architecture, you have a more correct approach. It could be added that the parser ignores such problems, but makepkg's refusal to do so makes it unnecessary.

Thank you!

**Comment by mindyourlifeguide** [comment] 2021-04-19 10:24
Sorry for my English, my words may not always convey the meaning accurately.

**Closed** 2021-05-21 15:15 UTC
