### ISSUE TITLE
Doesn't handle "debug" packages

### ISSUE THREAD

**Issue by kattjevfel** [Morganamilo/paru#76] opened 2020-11-04 14:02 UTC
I built dolphin-git-debug in a chroot and installed it, then when the was new commits (thus time to update) I got this:
```
:: Looking for devel upgrades
:: Resolving dependencies...
error: could not find all required packages:
    dolphin-git-debug (target)
```

And I noticed this:
```
:: Packages not in the AUR: dolphin-git-debug  ...  qt5-base-debug
```

Furthermore, when building packages via paru, even though I have debug set in makepkg.conf, it doesn't install it.

**Comment by Morganamilo** [comment] 2020-11-04 14:05
What command did you run?

**Comment by kattjevfel** [comment] 2020-11-04 14:44
To get the first error? Just plain `paru` or even `paru -Syu --aur`. For installing I used `paru -S dolphin-git`

**Comment by Morganamilo** [comment] 2020-11-04 18:02
Weird, the fact that it's a debug shouldn't matter really. Any package that's not in the AUR, paru should just ignore, not error out on. Afaik having debug enabled in your makepkg.conf will cause `makepkg --package` list to show the debug packages. But otherwise don't see how paru would trip up like this.

**Comment by Morganamilo** [comment] 2020-11-04 18:17
Anyway, the "not in the AUR" message should be fixed. But I can't reproduce it actually erroring out.

**Comment by kattjevfel** [comment] 2020-11-04 23:00
Adding `debug` to my makepkg.conf was an attempt to make things work, as I thought perhaps the package needed to be built with paru to make it recognise it.

There's 2 issues in this, not sure if I should split them or not. 
1. paru does not install -debug packages automatically
2. paru mysteriously refuses to upgrade devel (in the paru sense) packages when they have -debug (this is getting messy T_T)

Better reproduction steps, to clarify exactly how I ended here:
1. Install dolphin-git via paru
2. Build and install dolphin-git with debug in chroot
3. Either wait for new commits or set a previous commit in `~/.cache/paru/devel.json`
4. Run `paru -Syu --aur`
5. paru, pacman or makepkg throws the error.

`paru v1.0.2.r7.g960fb1a - libalpm v12.0.2`
I also tested with pacman-git but no difference (other than that I found out paru doesn't build with pacman-git)

**Comment by Morganamilo** [comment] 2020-11-04 23:11
> paru does not install -debug packages automatically

Yes. It's behind a config option. Even then that option means paru will install debug packages is a package produces them. Not force the package to make them.

> paru mysteriously refuses to upgrade devel (in the paru sense) packages when they have -debug (this is getting messy T_T)


Not sure exactly what you mean here. But as debug pacakgs don't exist in the air paru will never list them as needing to update. But when the regular pacakge needs to update paru will also install the updated debug packages. Which is fine, as a debug packages is never going to update without the main pacakge updating.

> Better reproduction steps, to clarify exactly how I ended here:

Now this is starting to make sense. When I tried I didn't realize it was a devel update. A recent commit changed how devel packages work with split pacakges. That's probably the issue.

> I also tested with pacman-git but no difference (other than that I found out paru doesn't build with pacman-git)


It does, or atleast should.

**Comment by kattjevfel** [comment] 2020-11-04 23:16
> > paru does not install -debug packages automatically
> 
> Yes. It's behind a config option. Even then that option means paru will install debug packages is a package produces them. Not force the package to make them.

I wasn't aware of this, I figured it was by default since both makepkg and yay does this, I'll look into it.

> > Better reproduction steps, to clarify exactly how I ended here:
> 
> Now this is starting to make sense. When I tried I didn't realize it was a devel update. A recent commit changed how devel packages work with split pacakges. That's probably the issue.

Terribly sorry for the confusion, I'm not very good at writing tickets or explaining things :/

> > I also tested with pacman-git but no difference (other than that I found out paru doesn't build with pacman-git)
> 
> It does, or atleast should.

See other ticket I created

**Closed** 2020-11-05 09:45 UTC
