### ISSUE TITLE
Feature request: customizepkg support

### ISSUE THREAD

**Issue by PythonNut** [Morganamilo/paru#260] opened 2021-02-22 22:19 UTC
There is a similar issue for `yay` at https://github.com/Jguer/yay/issues/336. [`customizepkg`](https://aur.archlinux.org/packages/customizepkg/) is a tool to automatically patch `PKGBUILD` files before the package is built. A couple [variants](https://aur.archlinux.org/packages/customizepkg-patching/) [exist](https://aur.archlinux.org/packages/customizepkg-scripting/) which provide the same interface but allow users to specify their modifications in different ways.

I personally have used it to modify the config of kernels that I install from the AUR to enable certain features that are disabled by default. I'm sure others have their own use-cases for this functionality. However If you decide that `customizepkg` is a bit gross and decide not to add support I would totally understand.

**Comment by Morganamilo** [comment] 2021-02-22 22:19
I don't get why you would use this rather than just editing the pkgbuild.

**Comment by PythonNut** [comment] 2021-02-24 00:50
I think substantial time is saved if both of the following are true:

1. The package is built many times
2. The edits required demand substantial effort

**Comment by Morganamilo** [comment] 2021-02-24 03:25
> One example is setting some kernel configuration options, which could be done by writing a patch and inserting the command to patch the kernel config at the right moment. If you rebuild your kernel often, then this becomes tedious.

Isn't that what customizopkg does though? Generate so e patch that you have to apply at the right moment.

How is that any better than just editing the config file?

**Comment by Aetf** [comment] 2021-02-25 19:22
Would also love to have customizepkg support.

My use case is to apply a set of patches to some packages in the official repo/AUR. These are usually small tweaks of a few lines in the source code, which are not generally useful enough to be upstreamed, or included in the official PKGBUILD.

Because these patches are small, they can usually apply to several version updates without modification. However, the experience during updates isn't ideal.

Right now, in the case of the official repo, this has to be done manually:

* pay careful attention to the updated package list during `paru -Syu` and skip the package I want to patch
* apply patches manually by `paru -G pkgname` and edit the PKGBUILD
* build and install

The process is repetitive and error-prone as I may easily overlook the updated package list and install an unpatched version.

In the case of the AUR, this can be somewhat automated by commit changes in `~/.cache/paru/clone/pkgname`, and paru will merge those commits during update. But it doesn't feel right to have important information in `~/.cache`. It's also hard to manage.

I know I could just copy the PKGBUILD and publish separate AUR packages, but I feel that's overkill for this use case and I would need to pay extra attentions to keep track of updates in original PKGBUILDs.

**Comment by Aetf** [comment] 2021-02-25 19:23
> > One example is setting some kernel configuration options, which could be done by writing a patch and inserting the command to patch the kernel config at the right moment. If you rebuild your kernel often, then this becomes tedious.
> 
> Isn't that what customizopkg does though? Generate so e patch that you have to apply at the right moment.
> 
> How is that any better than just editing the config file?

I guess the point is customizepkg can apply the patch automatically?

**Comment by Morganamilo** [comment] 2021-02-25 19:35
> Right now, in the case of the official repo, this has to be done manually

That may be out of scope anyway even if customizepkg was supported. Paru just uses asp for the repo pkgbuilds. Maybe that has some ability to merge changes but I'm unsure.

> In the case of the AUR, this can be somewhat automated by commit changes in ~/.cache/paru/clone/pkgname, and paru will merge those commits during update. But it doesn't feel right to have important information in ~/.cache. It's also hard to manage.

You can just configure it to be somewhere else. I don't get how it's hard to manage though.

> I guess the point is customizepkg can apply the patch automatically?

As you already noted git will just handle this when you commit changes.

**Comment by Aetf** [comment] 2021-02-25 22:02
> That may be out of scope anyway even if customizepkg was supported. Paru just uses asp for the repo pkgbuilds. Maybe that has some ability to merge changes but I'm unsure.

I think customizepkg support can be the first step. For repo packages, another missing piece is the ability to force build from source for certain repo packages every time there's an update. Then customizepkg can be applied to modify the pkgbuild before building.

> You can just configure it to be somewhere else.

True. But still semantically it *is* the cache used and modified by paru, and now I'm adding my own changes to it.

Maybe it's just me not completely understanding how paru handles AUR clones, but I had a few times where paru resets HEAD to an old commit before updates, and I had to use `git reflog` to find the lost commit. And I failed to find where does paru keep the commit hash.
This is probably my fault, as I was amending my custom commit but this experience makes me feel less secure about having changes in those clones.

> I don't get how it's hard to manage though.

The above, and it's not clear from the outside which package contains custom patches; versus having a set of configuration files in a centralized place, possibly managed by VCS itself.
 
> As you already noted git will just handle this when you commit changes.

As I mentioned above, customizepkg is more manageable and could potentially be extended to support repo packages.
I understand this may be out of scope. But having customizepkg has great potential to enable a [Gentoo portage patches](https://wiki.gentoo.org/wiki//etc/portage/patches) like system, so we can enjoy the binary package already built and at the same time have the ability to build our own patched version as needed.

**Comment by Morganamilo** [comment] 2021-02-25 22:20
Repo packages would take a lot of effort to support. So deffinetly out of scope.

You can also think of .git as a cache that git manages but that's fine right?

If paru loses a commit you made then please open an issue on it.

Having all the patches in one place I can see as an advantage though. You can find out your pattern my looking for commits you are the author of.

Anyway despite that being an advantage I think the current system is good enough.

**Comment by Morganamilo** [comment] 2021-02-25 22:22
Also, I think it would be cool to see customizepkg be made into a libmakepkg plugin. Allowing it to just work with every pkgbuild and not needing aurheper support.

**Comment by Aetf** [comment] 2021-02-26 01:05
> You can also think of .git as a cache that git manages but that's fine right?

Yeah. But you won't normally directly edit files in .git (Ok I know there are hooks etc that are local only).

> Anyway despite that being an advantage I think the current system is good enough.

I can live with it. It's just a QoL improvement anyway.

As for losing commit, I'll report if I can figure out how to reproduce.

**Comment by trbn1** [comment] 2021-03-19 15:41
What I'm currently using to achieve this with a different AUR helper is a pre-build command, which simply executes a command `customizepkg --modify` in the folder with PKGBUILD before building the package. Maybe something like this could be implemented and added as a config option for now?

**Comment by andrewerf** [comment] 2021-08-08 11:37
> Repo packages would take a lot of effort to support. So deffinetly out of scope.

Why actually? What is the big difference between repo and aur which makes it hard to support?

**Comment by Morganamilo** [comment] 2021-08-08 13:03
Different API, different data types, etc.

**Comment by Maik93** [comment] 2021-08-17 08:00
A different approach could be this one: https://github.com/Jguer/yay/issues/336#issuecomment-813433797
`makepkg` is simply wrapped in order to call `customizepkg` first. This should work in paru too, without any modification, isn't it?

**Closed** 2021-10-13 13:00 UTC

**Comment by HaleTom** [comment] 2025-05-05 13:03
PreBuildCommand was introduced as a way to use `customizepkg`, see #539 .

**Comment by rharish101** [comment] 2025-08-09 10:41
I'm not able to change dependencies with customizepkg, since it seems that it is run after paru decides which dependencies to install.

**Comment by chocolateboy** [comment] 2025-11-14 12:11
> I'd consider that a safety feature, I can review a PKGBUILD before it is evaluated

It's orthogonal to safety. It doesn't (wouldn't) replace reviewing the PKGBUILD, and, as mentioned, the current (RPC-based) resolver (which would remain the default) is for performance and reliability. An alternative (probably better) solution would be to provide a way to override (add/remove/replace) dependencies statically (per package), leaving customizepkg for patches.

**Comment by HaleTom** [comment] 2026-02-03 15:20
Here's how I set this up:

`~/.config/paru/paru.conf`

```
[bin]
# Note: these variables shouldn't be quoted -- any quotes are passed literally
PreBuildCommand = command -v customize-pkg-modify > /dev/null &&  customize-pkg-modify $PKGBASE $VERSION
```

`~/bin/customize-pkg-modify`
```
#!/bin/bash
# Apply customizepkg config only if it exists for the current package.
# Assumes pkgbase is passed as $1

set -euo pipefail

die() { echo "${0##*/}: $*" >&2; exit 1; }

customizepkg=/usr/bin/customizepkg
dir=${XDG_CONFIG_HOME:-$HOME/.config}/customizepkg

[ $# -lt 1 ] && die "Expected first argument to be pkgbase"
pkgbase=$1
config="$dir/$pkgbase"
if [ ! -f "$config" ]; then
  exit 0
fi

echo "Applying $config"
[ ! -x "$customizepkg" ] && die "$customizepkg not executable"
"$customizepkg" --modify
```

A good HOWTO guide: https://www.supertechcrew.com/customizing-aur-arch-package-with-customizepkg/

**Comment by ArjixWasTaken** [comment] 2026-02-03 17:36
@HaleTom this alone is enough

`/etc/paru.conf`
```ini
[bin]
PreBuildCommand = customizepkg -m
```
