### ISSUE TITLE
"Duplicate package"

### ISSUE THREAD

**Issue by RubenKelevra** [Morganamilo/paru#773] opened 2022-06-12 16:38 UTC
### Affected Version
**paru v1.10.0 - libalpm v13.0.1**

### Description
paru prints out an error about "duplicate package" on an update, just because it had previously built a package to its local aur repository, which is now provided by chaotic aur.

### Output

```
$ paru -Syu
[sudo] password for rubenk: 
no new news
:: Synchronizing package databases...
 core-x86-64-v3 is up to date
 extra-x86-64-v3 is up to date
 community-x86-64-v3 is up to date
 core is up to date
 extra is up to date
 community                                            6.7 MiB  2.48 MiB/s 00:03 [----------------------------------------------] 100%
 multilib is up to date
 endeavouros is up to date
 chaotic-aur is up to date
 aur-chroot-builds is up to date
:: Looking for AUR upgrades
:: Looking for devel upgrades
error: timed out looking for devel update: https://gitlab.freedesktop.org/hadess/iio-sensor-proxy
15 extra/libphonenumber                                 1:8.12.49-1                  -> 1:8.12.50-1
14 community/freecad                                    0.19.4-2                     -> 0.19.4-3
13 multilib/yabridge                                    4.0.0-4                      -> 4.0.1-1
12 multilib/yabridgectl                                 4.0.0-4                      -> 4.0.1-1
11 chaotic-aur/nodejs-nativefier                        47.1.3-1                     -> 47.2.0-1
10 aur-chroot-builds/drawio-desktop                     19.0.0-1                     -> 19.0.2-1
 9 aur-chroot-builds/git-cola                           4.0.0-1                      -> 4.0.1-1
 8 aur-chroot-builds/git-remote-ipld-git                1:0.0.0.r0.g2f4756ae2-1      -> 1:0.0.0.r0.g2f4756ae2-2
 7 aur-chroot-builds/nodejs-nativefier                  47.1.3-1                     -> 47.2.0-1
 6 aur-chroot-builds/python-jaraco.packaging            9.0.0-1                      -> 9.0.0-2
 5 aur-chroot-builds/simutrans-extended-pak128.britain  r4300.4a5f21f4e-1            -> r4326.91f432b78-1
 4 aur-chroot-builds-devel/appimagelauncher             2.2.0-6                      -> latest-commit
 3 aur-chroot-builds-devel/go-ipfs-git                  1:0.13.0rc1.r27.g2e170a430-1 -> latest-commit
 2 aur-chroot-builds-devel/proton-ge-custom-native      2:GE.Proton7.20-1            -> latest-commit
 1 aur-chroot-builds-devel/simutrans-extended-git       r20982.36ce00887-1           -> latest-commit
:: Packages to exclude (eg: 1 2 3, 1-3):
:: 
:: Resolving dependencies...
error: duplicate packages: nodejs-nativefier
```

**Comment by Morganamilo** [comment] 2022-06-18 17:19
Duplicate of #617 

Having more examples is nice though.

**Closed by Morganamilo** 2022-06-18 17:19 UTC
